version: '3'

services:
  docker-mysql:
    image : mysql
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spring_user"
    restart: always
    networks:
      - web
       
  spring-crud:
   image: sb-crud
   links:
    - docker-mysql:mysql
   ports:
     - 8080
   environment:
     - SERVICE_PORTS=8080
   deploy:
     replicas: 2
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - spring-crud
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web

networks:
    web:
      driver: overlay